stages:
  - merge_to_dev
  - merge_to_prod

merge_to_dev:
  stage: merge_to_dev
  script:
    - git config --global user.email "mohamednabeel321@gmail.com"
    - git config --global user.name "nabeelmohamed"
    - git remote set-url origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/nabeeldemos/my-awesome-project.git
    - git fetch origin
    - git checkout dev
    - git merge origin/main
    - git push origin dev
  only:
    - main

merge_to_prod:
  stage: merge_to_prod
  script:
    - git config --global user.email "mohamednabeel321@gmail.com"
    - git config --global user.name "nabeelmohamed"
    - git remote set-url origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/nabeeldemos/my-awesome-project.git
    - git fetch origin
    - git checkout prod
    - git merge origin/dev
    - git push origin prod
  only:
    - dev
